version: '3'
services:
        jupyter:
                image: jupyter/tensorflow-notebook
                ports:
                - 8888
                container_name: jupyter
                volumes:
                - ${LOCAL_WORKING_DIR}:/home/jovyan
                command: "start-notebook.sh \
                          --NotebookApp.password=${ACCESS_TOKEN}"
